plugins {
    id 'base'
}

def javaVersion = 21

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion)
        }
    }

    layout.buildDirectory = rootProject.layout.buildDirectory.dir(project.name)

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    rootProject.tasks.named('build') {
        dependsOn(tasks.named('build'))
    }

    rootProject.tasks.named('check') {
        dependsOn(tasks.named('check'))
    }
}
